#!/bin/python3 

import subprocess
import pyquran as pq 
import random 
import convert_numbers
import os 

button        = os.getenv("BLOCK_BUTTON", "Nope")
sura          = random.randint(1,114)
sura_name     = pq.quran.get_sura_name(sura)
aya           = random.choice(pq.quran.get_sura(sura, with_tashkeel=True))
title         = f'\t    <span font_family="serif" size="17pt" foreground="#FB617F">🕋 {sura_name}</span>'
aya_num       = f'<span font_family="serif" size="15pt">({convert_numbers.english_to_hindi(sura)})</span>'
aya_formatted = f'<span font_family="serif" size="15pt">{aya}</span>'
body          = f'{title} {aya_num} \n {aya_formatted}'

def send_notification(name , title , body):
    
    import gi
    gi.require_version('Gio', '2.0')
    from gi.repository import Gio

    Application = Gio.Application.new(name, Gio.ApplicationFlags.FLAGS_NONE)
    Application.register()
    Notification = Gio.Notification.new(title)
    Notification.set_body(body)
    Application.send_notification(None, Notification)

if button  :
    send_notification('random.aya', '' , body)

