#!/bin/bash

visual_icons=false
batdir="/sys/class/power_supply/BAT0"

status=$(cat "$batdir/status")
capacity=$(cat "$batdir/capacity")

warn() {
    local prompt="🪫Battery is low, connect the charger"
    notify-send "$prompt"
}

case "$status" in
    Discharging)
        [[ "$visual_icons" = true ]] && icon="🔋" || icon=""
        [[ "$capacity" -le 25 ]] && icon="🪫" ;; # warn
    Charging)
        [[ "$visual_icons" = true ]] && icon="🔌" || icon="c " ;;
    Full)
        [[ "$visual_icons" = true ]] && icon="⚡" || icon="f " ;;
    Unknown | "Not charging" | *)
        icon="" ;;
esac

echo "${icon}${capacity}%"
