#!/bin/bash


current_layout=$(setxkbmap -query  | grep layout | awk '{print $2}'| cut -d "," -f 1)

if [ $current_layout == "ar" ]; then
	setxkbmap -layout us,ar 
else
	setxkbmap -layout ar,us 
fi








