#!/bin/bash

case "$1" in
    toggle)
        pactl set-source-mute @DEFAULT_SOURCE@ toggle ;;
    mute)
        pactl set-source-mute @DEFAULT_SOURCE@ 1 ;;
    unmute)
        pactl set-source-mute @DEFAULT_SOURCE@ 1 ;;
    query)
        is_muted=$(pactl get-source-mute @DEFAULT_SOURCE@)
        [[ "$is_muted" == *"yes"* ]] && status="muted" || status="on"
        echo "mic: $status" ;;
    *)
        echo "Usage: ./sb-mic [toggle|mute|unmute|query]" ;;
esac
