#!/bin/python3 

import subprocess

command = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata | sed -n \'/title/{n;p}\' | cut -d \'\"\' -f 2"

song = subprocess.getoutput(command)

if song.split(" ")[0] != "Error" and song is not None :

    song = song[0:30] if len(song) > 30 else song 

    print(f"🎻 {song} ")
else:
	print("🎻")



