#!/bin/bash

uptime=$(uptime -p)

splitted=($uptime)
if [[ "$uptime" == *"day"* ]];then
    if [[ "$uptime" == *"hour"* ]];then
        days=${splitted[1]}; hours=${splitted[3]}; mins=${splitted[5]}
    else
        days=${splitted[1]}; hours="0"; mins=${splitted[3]}
    fi
    echo "up: ${days}d ${hours}h ${mins}m"

    elif [[ "$uptime" == *"hour"* ]];then
    hours=${splitted[1]}; mins=${splitted[3]}
    echo "up: ${hours}h ${mins}m"
else
    mins=${splitted[1]}
    echo "up: 0h ${mins}m"
fi
