#!/bin/bash

# soundeffect file path
soundfile="/usr/share/sounds/Yaru/stereo/audio-volume-change.oga"

playsound() {
    if [[ -f "$soundfile" ]]; then
        paplay "$soundfile"
    fi
}

format_volume() {
    local vol="$1"
    local is_muted=$(pactl get-sink-mute @DEFAULT_SINK@)
    if [[ "$is_muted" == *"yes"* ]]; then
        vol="muted"
    else
        vol=$(echo "$vol" | grep -Po '\d+(?=%)' | head -n 1)
    fi
    echo "vol: $vol"
}

case "$1" in
    inc)
        playsound
        pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
    dec)
        playsound
        pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
    query)
        volume=$(pactl get-sink-volume @DEFAULT_SINK@)
        format_volume "$volume" ;;
    mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
    *)
        echo "Usage: ./sb-volume [inc|dec|mute|query]" ;;
esac